passed_out_yr=input("which year you passed out from college")
print(passed_out_yr)
type_of_passed_out_yr=type(passed_out_yr)
print(type_of_passed_out_yr)
passed_out_yr=int(passed_out_yr)
type_2=type(passed_out_yr)
print(type_2)